### ISSUE TITLE
How is this extension supposed to work?

### ISSUE THREAD

**Issue by apahl** [bokeh/jupyterlab_bokeh#28]
Hi,

how is this extension supposed to work (a more extensive README would indeed be nice) ?
I installed the extension with `jupyter labextension install jupyterlab_bokeh` , and got a bunch of error messages for an optional dependency:

```
warning Error running install script for optional dependency: "/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.7.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v9.7.1/node-v9.7.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v9.7.1/node-v9.7.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v9.7.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v9.7.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pahl/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pahl/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pahl/.node-gyp/9.7.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pahl/.node-gyp/9.7.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/pahl/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pahl/.node-gyp/9.7.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc: In static member function ‘static void Canvas::ToBufferAsyncAfter(uv_work_t*)’:
../src/Canvas.cc:221:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     closure->pfn->Call(1, argv);
                               ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1568:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/Canvas.cc:226:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     closure->pfn->Call(2, argv);
                               ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1568:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
In file included from ../src/Canvas.cc:8:0:
../src/PNG.h: In function ‘cairo_status_t canvas_write_png(cairo_surface_t*, png_rw_ptr, void*)’:
../src/PNG.h:73:20: warning: variable ‘status’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     cairo_status_t status = CAIRO_STATUS_SUCCESS;
                    ^~~~~~
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:9:0:
../src/Image.h:19:10: fatal error: gif_lib.h: No such file or directory
 #include <gif_lib.h>
          ^~~~~~~~~~~
compilation terminated.
canvas.target.mk:127: recipe for target 'Release/obj.target/canvas/src/CanvasPattern.o' failed
make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
make: Leaving directory '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pahl/.config/yarn/global/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.jssuccess Saved lockfile.
.........
Done in 35.73s
```

But  otherwise the built seems to have worked.
However, after a restart of the server, I stll do not see any Bokeh plots in the JupyterLab notebook.
Am I missing an additional installation step? Do I have to activate the extension somewhere?

Many thanks.

Kind regards,  
Axel

**Comment by bryevdv** [comment]
cc @canavandl

**Comment by bryevdv** [comment]
`jupyter labextension install jupyterlab_bokeh` should be the only action needed to install. Offhand, it looks like it's failing to build Cairo. But bokeh does not depend on Cairo so not sure why it's trying to build it at all unless it's some jupyter lab thing.

**Comment by canavandl** [comment]
It's an upstream jupyterlab issue (https://github.com/jupyterlab/jupyterlab/issues/3665). The errors should be able to be ignored and the build should complete correctly.

Can you share the output of ``jupyter labextension list`` after you've tried to install the extension? I'd also suggest trying to hard refresh your browser when you launch jupyterlab, in case there's some caching issue.

**Comment by bryevdv** [comment]
I do wish `jupyter labextension` was quieter by default. All this output is mostly confusing and not helpful.

**Comment by rcthomas** [comment]
I've installed it successfully, bokeh's listed in the labextension list output.  But I don't see any clue in JupyterLab that tells me it's there.  What should I look for?  Is there a hello world I can run besides something that just tells me "JavaScript output is disabled in JupyterLab?"  Thanks.

**Comment by bryevdv** [comment]
>  Is there a hello world I can run besides something that just tells me "JavaScript output is disabled in JupyterLab?" Thanks.

If it is saying that, then it specifically is *not* trying to use the extension. What version of Bokeh do you have installed?

**Comment by rcthomas** [comment]
```
> conda list | grep bokeh
bokeh                     0.12.5                   py36_1
r-rbokeh                  0.5.0                  r3.4.1_0
```

Is there a minimum version required?

**Comment by bryevdv** [comment]
Yes, JupyterLab support was only introduced in version `0.12.9`:

https://bokeh.github.io/blog/2017/9/12/release-0-12-9/

**Comment by rcthomas** [comment]
Thanks!  That works!  (Sorry to hijack @apahl's thread, but maybe it helps?)

**Comment by sbailey** [comment]
+1 for @rcthomas problem + @bryevdv bokeh upgrade suggestion, which appears related to @apahl original post: I also had an apparent error message running `jupyter labextension install jupyterlab_bokeh` that sent me off on a wild goose chase of gobject-2.0, libz, ... dependencies when the actual problem was just that I needed to upgrade bokeh.

Is there any way that `jupyter labextension install jupyterlab_bokeh` dependency checks could catch that bokeh itself needs to be upgraded and print a helpful error message about that?

**Comment by apahl** [comment]
@canavandl : Thanks for coming back to me.  
The output of `jupyter labextension list` is:  
```
$ jupyter labextension list
JupyterLab v0.31.11
Known labextensions:
   app dir: /home/pahl/anaconda3/envs/chem/share/jupyter/lab
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0  enabled  OK
```
and this is my full conda env:  
```
$ conda list
# packages in environment at /home/pahl/anaconda3/envs/chem:
#
alabaster                 0.7.10                   py36_1    conda-forge
altair                    1.2.1                      py_0    conda-forge
arrow-cpp                 0.8.0                    py36_4    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
autopep8                  1.3.3                      py_0    conda-forge
babel                     2.5.3                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bokeh                     0.12.14                  py36_0    conda-forge
boost                     1.63.0           py36h415b752_1    rdkit
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.1.18                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
cairocffi                 0.8.0                     <pip>
CairoSVG                  2.1.3                     <pip>
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.2                      py_0    conda-forge
cryptography              2.1.4                    py36_0    conda-forge
cssselect2                0.2.1                     <pip>
cycler                    0.10.0                   py36_0    conda-forge
dask                      0.17.1                     py_1    conda-forge
dask-core                 0.17.1                     py_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py36_0    conda-forge
defusedxml                0.5.0                     <pip>
distributed               1.21.2                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
easydict                  1.7                       <pip>
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                         0    conda-forge
flake8                    3.5.0                    py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.3a1                    py36_0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
grequests                 0.3.0                    py36_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
holoviews                 1.9.5                    py36_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idisplay                  0.1.2                     <pip>
idna                      2.6                      py36_1    conda-forge
imagesize                 1.0.0                    py36_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.2.1                    py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.1.2                    py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jedi                      0.11.1                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter                   1.0.0                     <pip>
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.4.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.1.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
jupyterlab                0.31.11                  py36_1    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
lancet                    0.9.0                    py36_0    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.15                        1    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.7                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.1.1                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.0                    py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
memory_profiler           0.50.0                   py36_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
msgpack-python            0.5.5                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                           1    rdkit
networkx                  2.1                      py36_0    conda-forge
notebook                  5.4.0                    py36_0    conda-forge
numpy                     1.14.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py36_0    conda-forge
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2n                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.22.0                   py36_0    conda-forge
pandoc                    2.1.2                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
param                     1.5.1                    py36_0    conda-forge
parquet-cpp               1.4.0.pre                     2    conda-forge
parso                     0.1.1                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patsy                     0.5.0                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.0.0                    py36_0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pixman                    0.34.0                        1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.3                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py3Dmol                   0.7.0                     <pip>
pyarrow                   0.8.0                    py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyopenssl                 17.5.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2018.3                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_3    conda-forge
qt                        5.6.2                         7    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
rdkit                     2017.09.3.0              py36_1    rdkit
readline                  7.0                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
requests-cache            0.4.13                   py36_0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                38.5.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snakeviz                  0.4.2            py36h8fadade_0  
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.7.1                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tinycss2                  0.6.1                     <pip>
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vega                      0.4.4                    py36_1    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.1.4                    py36_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.3                         2    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
This is the code that I am trying to run and the result:  
![jlab_bokeh](https://user-images.githubusercontent.com/9406836/37079323-831eba88-21e2-11e8-89ee-5f196434f324.png)

As you can see, the output cell remains completely empty (I also tried other examples). When I open the Notebook directly from the Jupyter **Notebook** server, the plots are there.  

Many thanks for your help.  
Kind regards,  
Axel

**Comment by philippjfr** [comment]
@apahl Looks like you are trying to run HoloViews. We only just added support for JupyterLab in HoloViews last week and currently there is no release that supports it yet, once 1.10 is released you'll 
be able to use it once you have to installed the [jupyterlab_holoviews](https://github.com/pyviz/jupyterlab_holoviews) extension.

**Comment by apahl** [comment]
Ah ok, I thought since I use the bokeh backend, the bokeh extension would be sufficient.  
This explains it, then.  
Many thanks for your help.

Kind regards,  
Axel

**Comment by philippjfr** [comment]
>I thought since I use the bokeh backend, the bokeh extension would be sufficient.

For static plots it technically would have been sufficient but HoloViews offers bidirectional communication in the notebook, which required shipping our own custom extension.
