### ISSUE TITLE
Install jupyterlab_bokeh got errors

### ISSUE THREAD

**Issue by openthings** [bokeh/jupyterlab_bokeh#43]
I am using JupyterLab 0.32.1 on Kubernetes based ubuntu16.04.3LTS，install jupyterlab_bokeh got errors as following：

jovyan@jupyter-supermap:~$ jupyter labextension install jupyterlab_bokeh
> /opt/conda/bin/npm pack jupyterlab_bokeh
jupyterlab_bokeh-0.5.0.tgz
> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 188.54s.
> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
$ webpack --config webpack.prod.config.js
/opt/conda/share/jupyter/lab/staging/node_modules/html-webpack-plugin/index.js:14
  this.options = _.extend({
                   ^

TypeError: _.extend is not a function
    at new HtmlWebpackPlugin (/opt/conda/share/jupyter/lab/staging/node_modules/html-webpack-plugin/index.js:14:20)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/webpack.config.js:169:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/webpack.prod.config.js:5:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack --config webpack.prod.config.js
Directory: /opt/conda/share/jupyter/lab/staging
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/opt/conda/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by canavandl** [comment]
As noted in https://github.com/bokeh/jupyterlab_bokeh/issues/40, the problem appears to be related to rebuilding jupyterlab with node v10. I'd suggest downgrading to node 8 or 9 and trying again until we've resolved this.

**Comment by canavandl** [comment]
This issue is an upstream problem with JupyterLab (https://github.com/jupyterlab/jupyterlab/issues/4986), so I'm going to mark as closed.

If jupyterlab begins to support node@10 and there's a problem with this extension, please reopen this issue.
